### ISSUE TITLE
How to set 

### ISSUE THREAD

**Issue by danfarhat** [SiddheshNan/ThingESP-Arduino-Library#2]
Hello
i want to add ThingESP8266 thing("","","");
to void setup how to setup
please help me

**Comment by SiddheshNan** [comment]
Hello, can you share your Arduino code?

**Comment by danfarhat** [comment]
#include <ESP8266WiFi.h>          //https://github.com/esp8266/Arduino

//needed for library
#include <DNSServer.h>
#include <ESP8266WebServer.h>
#include <WiFiManager.h>         //https://github.com/tzapu/WiFiManager

#include <ThingESP.h>
const char*        username                   = "user";
const char*        projectName                   = "test";
const char*        credentials                   = "1234567890";




String        _ssid                   = "";
String        _pass                   = "";

 
int LED = LED_BUILTIN;
int var = 0;
unsigned long previousMillis = 0;
const long INTERVAL = 6000;
String dannn;
void setup()
{
  
  Serial.begin(115200);
//  WiFiManager wifiManager;
//  wifiManager.autoConnect("AutoConnectAP");
  pinMode(LED, OUTPUT);

ThingESP8266 thing(username,projectName,credentials);
thing.SetWiFi(_ssid.c_str(), _pass.c_str());

  thing.initDevice();
}

String HandleResponse(String query)
{

  if (query == "on")
  {
    digitalWrite(LED, 0);
    return "⚡ : Electricity IS ON";
  }

  else if (query == "off")
  {
    digitalWrite(LED, 1);
    return "🔌 : Electricity IS OFF"; //   🔌   💡
  }

  else if (query == "s")
    return digitalRead(LED) ? "🔌  ELECTRICITY IS OFF" : "⚡  ELECTRICITY IS ON";

  else
    return "Your query was invalid.. on or off";
}

void loop()
{
 

  thing.Handle();
  delay(2000);
  
  dany();
}

void dany() {
  delay(6000);

  if ( var == 0 && millis() - previousMillis >= INTERVAL)
  {
    Serial.println(var);
    previousMillis = millis();
    String msg = digitalRead(LED) ? "LED is OFF" : "⚡... ELECTRICITY IS ON...";
   thing.sendMsg("+96100000", msg);
    var = 1;
  }

}

**Comment by SiddheshNan** [comment]
Hello,
You cannot declare - ThingESP8266 thing("", "", "") inside the setup method.
you have to declare it globally, above the setup method since thing.Handle() method is getting called in the loop function, hence we need that thing variable global.

Please check the example code here: https://github.com/SiddheshNan/ThingESP-Arduino-Library/blob/master/examples/ESP8266-send-message/ESP8266-send-message.ino

Also, there is a huge delay in the loop() method & dany() method, it will restrict the ESP from reading any network requests, and possibly the messages won't reach the ESP.
Consider removing the delay and using millis instead.
You can find that example code here: https://www.arduino.cc/en/Tutorial/BuiltInExamples/BlinkWithoutDelay

Hope this helps!

**Comment by danfarhat** [comment]
Hello Dear
Thx for your reply
i want to change in this ThingESP8266 thing("", "", "")
by eeprom i can't change in global declaration i want to change in void setup or loop
